"""remove phone fields

Revision ID: 2381587a0494
Revises: 
Create Date: 2023-08-06 11:55:34.762422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2381587a0494"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("_phone_number")
        batch_op.drop_column("country_code")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("country_code", sa.VARCHAR(length=8), nullable=True)
        )
        batch_op.add_column(
            sa.Column("_phone_number", sa.VARCHAR(length=20), nullable=True)
        )

    # ### end Alembic commands ###
